local data = require "main.data"

go.property("move", vmath.vector3())

local function spawn(self)
	data.parcels = data.parcels - 1
	if data.parcels <= 0 then
		timer.cancel(self.handle)
	end
	local pos = go.get_position()
	pos = pos + self.move * data.TILE
	local obj = factory.create("#parcel-fac", pos, nil, {move = self.dir})
	msg.post("level", "addobj", {url = obj})
end

function init(self)
	self.handle = timer.delay(3 - (data.level / 5), true, spawn)
end

